exclude:   [ "less", "gitignore", "nicoespeon.sublime-project", "nicoespeon.sublime-workspace" ]

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]

permalink:  /:categories/:year/:month/:title
paginate: 7
paginate_path: "/page:num"
paginate_per_category: true
default_category: "en"

safe: false
url: http://nicoespeon.com

name: "@nicoespeon's blog"
description: "Freelance web-developer and project manager thoughts. LEAN management, OOCSS, Backbone.js, Marionette.js, EaselJS, front-end performance and a bit of PHP back-end frameworks."
default_locale:     "en"
authorized_locales: ["en", "fr"]
